/*
 * Hai mươi món khai vị bổ sung cho thực đơn.
 *
 * Mỗi món ghi đủ các trường như những món có sẵn: tên, mô tả ngắn, nguyên liệu, cách chế
 * biến, khẩu phần, lưu ý khi đặt và thời gian bếp cần. Trường "tim" là từ khóa tra ảnh
 * trên Wikimedia Commons, chỉ dùng lúc sinh dữ liệu chứ không ghi vào cơ sở dữ liệu.
 */
module.exports = [
  {
    slug: 'goi-cuon-tom-thit', dm: 'khaivi', gia: 95000, phut: 15,
    ten: 'Gỏi cuốn tôm thịt', tenEn: 'Fresh prawn and pork rolls',
    mota: 'Bánh tráng cuốn tay, chấm tương đậu phộng',
    motaEn: 'Hand-rolled rice paper with peanut dipping sauce',
    phan: 'Phần 10 cuốn', phanEn: '10 rolls',
    nguyenLieu: 'Bánh tráng, tôm sú luộc, thịt ba chỉ, bún tươi, hẹ, xà lách, rau thơm, tương đậu phộng.',
    nguyenLieuEn: 'Rice paper, boiled tiger prawn, pork belly, fresh vermicelli, garlic chives, lettuce, herbs, peanut dipping sauce.',
    cheBien: 'Cuốn tay từng cuốn khi khách gọi. Bánh tráng chỉ nhúng ẩm chứ không ngâm, để cuốn không bị nhão và vẫn nhìn rõ con tôm bên trong.',
    cheBienEn: 'Rolled by hand to order. The rice paper is only dampened, not soaked, so the roll stays firm and the prawn shows through.',
    luuY: 'Cuốn sẵn để lâu bánh tráng sẽ dai, bên mình chỉ cuốn khi khách gọi. Tương đậu phộng có đậu phộng, khách dị ứng báo trước để đổi nước chấm.',
    luuYEn: 'Rolled too far ahead the rice paper turns tough, so we roll to order. The dipping sauce contains peanuts; tell us if anyone is allergic and we will change it.',
    tim: 'goi cuon Vietnamese fresh spring roll',
  },
  {
    slug: 'banh-khot-vung-tau', dm: 'khaivi', gia: 135000, phut: 20,
    ten: 'Bánh khọt Vũng Tàu', tenEn: 'Vung Tau mini savoury pancakes',
    mota: 'Đổ khuôn gang, tôm tươi nguyên con',
    motaEn: 'Cooked in cast-iron moulds, topped with whole prawns',
    phan: 'Phần 12 cái', phanEn: '12 pieces',
    nguyenLieu: 'Bột gạo pha nước cốt dừa, tôm tươi, mỡ hành, tôm cháy, rau sống, nước mắm chua ngọt.',
    nguyenLieuEn: 'Rice batter with coconut milk, fresh prawn, scallion oil, dried prawn floss, garden herbs, sweet-and-sour fish sauce.',
    cheBien: 'Khuôn gang phải thật nóng và láng đủ dầu thì rìa bánh mới giòn còn lòng bánh vẫn mềm. Đổ từng mẻ mười hai cái, ra tới đâu dọn tới đó.',
    cheBienEn: 'The cast-iron mould must be very hot and well oiled so the rim crisps while the centre stays soft. Cooked twelve at a time and served straight away.',
    luuY: 'Bánh nguội sẽ mất độ giòn nên bên mình dọn theo mẻ. Có tôm, khách dị ứng hải sản báo trước.',
    luuYEn: 'They lose their crispness as they cool, so we serve them in batches. Contains prawn — please tell us about shellfish allergies.',
    tim: 'banh khot Vietnamese',
  },
  {
    slug: 'nem-nuong-nha-trang', dm: 'khaivi', gia: 155000, phut: 25,
    ten: 'Nem nướng Nha Trang', tenEn: 'Nha Trang grilled pork skewers',
    mota: 'Nướng than, cuốn bánh tráng, chấm tương nếp',
    motaEn: 'Charcoal grilled, rolled in rice paper with fermented rice sauce',
    phan: 'Phần 8 xiên', phanEn: '8 skewers',
    nguyenLieu: 'Thịt heo quết tay, tỏi, tiêu, bánh tráng, bánh hỏi, rau sống, tương nếp Nha Trang.',
    nguyenLieuEn: 'Hand-pounded minced pork, garlic, pepper, rice paper, fine rice vermicelli sheets, herbs, Nha Trang fermented rice sauce.',
    cheBien: 'Thịt quết tay cho dai chứ không xay nhuyễn bằng máy, ướp qua đêm rồi nướng than hoa. Tương nếp nấu từ gạo nếp lên men, không dùng tương ớt đóng chai.',
    cheBienEn: 'The pork is pounded by hand rather than machine-minced so it stays springy, marinated overnight and grilled over charcoal. The sauce is made from fermented glutinous rice, not bottled chilli sauce.',
    luuY: 'Nướng than có khói, không bố trí được ở phòng máy lạnh kín. Món ăn kèm nhiều rau nên một phần đủ cho ba người ăn chơi.',
    luuYEn: 'Charcoal grilling produces smoke and cannot be set up in a sealed air-conditioned room. Served with plenty of herbs, so one portion is enough for three as a snack.',
    tim: 'nem nuong Vietnamese grilled pork',
  },
  {
    slug: 'banh-beo-chen-hue', dm: 'khaivi', gia: 90000, phut: 20,
    ten: 'Bánh bèo chén Huế', tenEn: 'Hue steamed rice cakes',
    mota: 'Hấp từng chén nhỏ, tôm cháy và mỡ hành',
    motaEn: 'Steamed in individual bowls with prawn floss and scallion oil',
    phan: 'Phần 12 chén', phanEn: '12 bowls',
    nguyenLieu: 'Bột gạo, tôm cháy, mỡ hành, bánh mì chiên giòn, nước mắm pha loãng.',
    nguyenLieuEn: 'Rice flour, dried prawn floss, scallion oil, fried bread croutons, diluted fish sauce.',
    cheBien: 'Bột đổ vào từng chén sứ nhỏ rồi hấp, giữa mặt bánh lõm xuống một chút để giữ nhân. Rắc tôm cháy và chan mỡ hành ngay trước khi dọn.',
    cheBienEn: 'The batter is steamed in small porcelain bowls with a dimple in the middle to hold the topping. Prawn floss and scallion oil go on just before serving.',
    luuY: 'Bánh phải ăn nóng, để nguội sẽ cứng lại. Có tôm cháy, khách ăn chay báo trước để bên mình làm bản chay.',
    luuYEn: 'Best eaten warm; they firm up as they cool. Contains dried prawn — tell us in advance for a vegetarian version.',
    tim: 'banh beo Hue Vietnamese',
  },
  {
    slug: 'banh-bot-loc-la-chuoi', dm: 'khaivi', gia: 85000, phut: 25,
    ten: 'Bánh bột lọc lá chuối', tenEn: 'Tapioca dumplings in banana leaf',
    mota: 'Gói lá chuối, nhân tôm thịt',
    motaEn: 'Wrapped in banana leaf, filled with prawn and pork',
    phan: 'Phần 10 cái', phanEn: '10 pieces',
    nguyenLieu: 'Bột năng, tôm đất, thịt ba chỉ, lá chuối, hành phi, nước mắm ớt.',
    nguyenLieuEn: 'Tapioca starch, small river prawns, pork belly, banana leaf, fried shallots, chilli fish sauce.',
    cheBien: 'Bột nhồi nước sôi cho dẻo, gói lá chuối rồi hấp mười lăm phút. Lá chuối hơ lửa trước cho mềm, vừa dễ gói vừa để bánh thơm mùi lá.',
    cheBienEn: 'The dough is kneaded with boiling water, wrapped in banana leaf and steamed for fifteen minutes. The leaf is passed over a flame first so it softens and perfumes the dumpling.',
    luuY: 'Vỏ bánh dai nên trẻ nhỏ ăn cần cắt nhỏ. Có tôm, khách dị ứng hải sản báo trước.',
    luuYEn: 'The dough is chewy, so cut it up for small children. Contains prawn — please tell us about shellfish allergies.',
    tim: 'banh bot loc Vietnamese dumpling',
  },
  {
    slug: 'sup-mang-cua-ga-xe', dm: 'khaivi', gia: 105000, phut: 25,
    ten: 'Súp măng cua gà xé', tenEn: 'Crab and asparagus soup with shredded chicken',
    mota: 'Măng tây tươi, gà xé sợi',
    motaEn: 'Fresh asparagus with hand-shredded chicken',
    phan: 'Phần 4 chén', phanEn: '4 bowls',
    nguyenLieu: 'Măng tây tươi, thịt cua, ức gà xé, trứng gà, nước hầm gà, tiêu, ngò rí.',
    nguyenLieuEn: 'Fresh asparagus, crab meat, shredded chicken breast, egg, chicken stock, pepper, coriander.',
    cheBien: 'Nước hầm gà lọc trong, măng tây cho vào cuối cùng để giữ màu xanh và độ giòn. Trứng đánh tan rót thành sợi mỏng chứ không khuấy vón cục.',
    cheBienEn: 'The chicken stock is strained clear and the asparagus goes in last to keep its colour and bite. The egg is poured in a thin stream so it sets in ribbons rather than lumps.',
    luuY: 'Có thịt cua, khách dị ứng hải sản báo trước để bên mình làm bản chỉ có gà.',
    luuYEn: 'Contains crab; tell us in advance and we will make a chicken-only version.',
    tim: 'asparagus crab soup',
  },
  {
    slug: 'goi-ngo-sen-tom-thit', dm: 'khaivi', gia: 175000, phut: 20,
    ten: 'Gỏi ngó sen tôm thịt', tenEn: 'Lotus stem salad with prawn and pork',
    mota: 'Ngó sen Đồng Tháp, giòn và trắng',
    motaEn: 'Dong Thap lotus stems, crisp and pale',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Ngó sen Đồng Tháp, tôm sú, thịt ba chỉ, cà rốt, rau răm, đậu phộng rang, nước mắm chua ngọt.',
    nguyenLieuEn: 'Dong Thap lotus stems, tiger prawn, pork belly, carrot, Vietnamese coriander, roasted peanuts, sweet-and-sour fish sauce.',
    cheBien: 'Ngó sen ngâm nước chanh loãng cho trắng và giòn, vắt ráo rồi mới trộn. Trộn tay nhẹ để ngó sen không gãy vụn.',
    cheBienEn: 'The lotus stems soak in weak lemon water to stay pale and crisp, then are squeezed dry before dressing. Tossed gently by hand so they do not break.',
    luuY: 'Món trộn nên dọn ngay, để lâu sẽ ra nước. Có đậu phộng và hải sản, khách dị ứng báo trước.',
    luuYEn: 'A tossed salad, served immediately; left standing it weeps. Contains peanuts and shellfish — please tell us about allergies.',
    tim: 'lotus stem salad Vietnamese',
  },
  {
    slug: 'cha-ca-la-vong', dm: 'khaivi', gia: 185000, phut: 25,
    ten: 'Chả cá Lã Vọng', tenEn: 'La Vong turmeric fish',
    mota: 'Cá lăng ướp nghệ, rán trên chảo tại bàn',
    motaEn: 'Turmeric-marinated catfish, pan-fried at your table',
    phan: 'Phần 2-3 người', phanEn: 'Serves 2-3',
    nguyenLieu: 'Cá lăng phi lê, nghệ tươi, riềng, mẻ, thì là, hành lá, bún tươi, mắm tôm.',
    nguyenLieuEn: 'Catfish fillet, fresh turmeric, galangal, fermented rice starter, dill, spring onion, vermicelli, fermented shrimp paste.',
    cheBien: 'Cá ướp nghệ và mẻ nửa ngày cho thấm, rán sơ ở bếp rồi mang ra chảo nóng tại bàn, thả thì là và hành lá vào sau cùng.',
    cheBienEn: 'The fish marinates for half a day in turmeric and fermented rice starter, is part-fried in the kitchen, then finished in a hot pan at your table with dill and spring onion thrown in last.',
    luuY: 'Mắm tôm mùi rất đậm, bên mình có sẵn nước mắm thay thế nếu khách chưa quen. Chảo nóng đặt tại bàn nên cẩn thận với trẻ nhỏ.',
    luuYEn: 'The shrimp paste has a powerful aroma; we can serve fish sauce instead if you are not used to it. The hot pan sits on the table, so take care with small children.',
    tim: 'cha ca la vong Vietnamese turmeric fish',
  },
  {
    slug: 'hoanh-thanh-chien-gion', dm: 'khaivi', gia: 115000, phut: 15,
    ten: 'Hoành thánh chiên giòn', tenEn: 'Crispy fried wontons',
    mota: 'Nhân tôm thịt, chấm sốt chua ngọt',
    motaEn: 'Prawn and pork filling with sweet-and-sour sauce',
    phan: 'Phần 12 cái', phanEn: '12 pieces',
    nguyenLieu: 'Vỏ hoành thánh, tôm, thịt nạc dăm, nấm mèo, hành tím, sốt chua ngọt.',
    nguyenLieuEn: 'Wonton wrappers, prawn, pork shoulder, wood-ear mushroom, shallot, sweet-and-sour sauce.',
    cheBien: 'Gói xòe cánh rồi chiên ngập dầu ở lửa vừa, vớt ra để ráo trên vỉ chứ không để trên giấy, tránh bánh bị ỉu.',
    cheBienEn: 'Folded into open fans and deep-fried at medium heat, then drained on a rack rather than paper so they do not go soggy.',
    luuY: 'Món chiên nhiều dầu, không hợp với khách đang ăn kiêng. Có tôm trong nhân.',
    luuYEn: 'Deep-fried and rich, not suitable if you are eating light. The filling contains prawn.',
    tim: 'fried wonton',
  },
  {
    slug: 'goi-xoai-kho-ca-sac', dm: 'khaivi', gia: 125000, phut: 15,
    ten: 'Gỏi xoài khô cá sặc', tenEn: 'Green mango salad with dried gourami',
    mota: 'Xoài xanh bào sợi, khô cá sặc nướng',
    motaEn: 'Shredded green mango with grilled dried gourami',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Xoài xanh, khô cá sặc, hành tím, rau răm, ớt, đậu phộng rang, nước mắm chua ngọt.',
    nguyenLieuEn: 'Green mango, dried gourami fish, shallot, Vietnamese coriander, chilli, roasted peanuts, sweet-and-sour fish sauce.',
    cheBien: 'Khô cá sặc nướng than cho dậy mùi rồi xé sợi. Xoài bào ngay trước khi trộn để không bị thâm.',
    cheBienEn: 'The dried fish is grilled over charcoal until fragrant, then torn into strips. The mango is shredded at the last moment so it does not brown.',
    luuY: 'Khô cá mặn và có mùi đặc trưng, khách chưa quen nên gọi phần nhỏ. Món chua, không hợp người đau dạ dày.',
    luuYEn: 'The dried fish is salty with a strong aroma; order a small portion if it is new to you. The salad is sour and not kind to a sensitive stomach.',
    tim: 'green mango salad',
  },
  {
    slug: 'chao-tom-boc-mia', dm: 'khaivi', gia: 165000, phut: 25,
    ten: 'Chạo tôm bọc mía', tenEn: 'Prawn paste on sugarcane',
    mota: 'Tôm quết bọc quanh khúc mía, nướng than',
    motaEn: 'Pounded prawn wrapped around sugarcane and charcoal grilled',
    phan: 'Phần 8 khúc', phanEn: '8 skewers',
    nguyenLieu: 'Tôm sú quết, mỡ heo, mía tươi, bánh tráng, rau sống, nước chấm đậu phộng.',
    nguyenLieuEn: 'Pounded tiger prawn, pork fat, fresh sugarcane, rice paper, garden herbs, peanut dipping sauce.',
    cheBien: 'Tôm quết tay cùng một ít mỡ heo cho kết dính, bọc quanh khúc mía rồi nướng than. Mía vừa làm que vừa tiết nước ngọt vào phần tôm khi nướng.',
    cheBienEn: 'The prawn is pounded by hand with a little pork fat to bind, moulded around the cane and grilled over charcoal. The cane doubles as a skewer and sweetens the prawn as it cooks.',
    luuY: 'Khúc mía dùng để cầm và nhai lấy nước chứ không nuốt bã. Có tôm và đậu phộng.',
    luuYEn: 'The cane is there to hold and to chew for its juice, not to swallow. Contains prawn and peanuts.',
    tim: 'chao tom prawn sugarcane Vietnamese',
  },
  {
    slug: 'banh-uot-thit-nuong', dm: 'khaivi', gia: 120000, phut: 20,
    ten: 'Bánh ướt thịt nướng', tenEn: 'Steamed rice sheets with grilled pork',
    mota: 'Bánh tráng ướt cuốn thịt nướng than',
    motaEn: 'Soft rice sheets rolled around charcoal-grilled pork',
    phan: 'Phần 8 cuốn', phanEn: '8 rolls',
    nguyenLieu: 'Bánh ướt, thịt nạc vai nướng, xà lách, dưa leo, rau thơm, nước chấm đậu phộng.',
    nguyenLieuEn: 'Fresh rice sheets, grilled pork shoulder, lettuce, cucumber, herbs, peanut dipping sauce.',
    cheBien: 'Thịt ướp sả tỏi nướng than cho xém cạnh, cuốn ngay vào bánh ướt còn ấm để bánh không bị khô và dính vào nhau.',
    cheBienEn: 'The pork is marinated with lemongrass and garlic, grilled until the edges char, and rolled straight into warm rice sheets so they do not dry or stick together.',
    luuY: 'Bánh ướt để lâu sẽ dính, bên mình cuốn khi khách gọi. Nước chấm có đậu phộng.',
    luuYEn: 'The rice sheets stick together if left standing, so we roll them to order. The dipping sauce contains peanuts.',
    tim: 'banh uot thit nuong Vietnamese',
  },
  {
    slug: 'tai-heo-cuon-ngu-sac', dm: 'khaivi', gia: 135000, phut: 20,
    ten: 'Tai heo cuốn ngũ sắc', tenEn: 'Five-colour pork ear rolls',
    mota: 'Tai heo luộc giòn cuốn rau củ',
    motaEn: 'Crisp boiled pork ear rolled with vegetables',
    phan: 'Phần 10 cuốn', phanEn: '10 rolls',
    nguyenLieu: 'Tai heo, cà rốt, dưa leo, ớt chuông, hẹ, bánh tráng, nước mắm gừng.',
    nguyenLieuEn: 'Pork ear, carrot, cucumber, bell pepper, garlic chives, rice paper, ginger fish sauce.',
    cheBien: 'Tai heo luộc vừa chín tới rồi ngâm nước đá cho giòn, thái mỏng. Cuốn cùng rau củ thái sợi năm màu, chấm nước mắm gừng.',
    cheBienEn: 'The pork ear is boiled just until done, shocked in iced water to stay crunchy, then finely sliced and rolled with vegetables cut in five colours, served with ginger fish sauce.',
    luuY: 'Tai heo có độ sần đặc trưng, khách chưa quen nên thử trước. Món nguội, không hâm lại được.',
    luuYEn: 'Pork ear has a distinctive crunch that not everyone expects; try a piece first. Served cold and cannot be reheated.',
    tim: 'pork ear salad Vietnamese',
  },
  {
    slug: 'muc-chien-nuoc-mam', dm: 'khaivi', gia: 195000, phut: 20,
    ten: 'Mực chiên nước mắm', tenEn: 'Squid fried in fish sauce',
    mota: 'Mực ống tươi, sốt mắm tỏi sánh',
    motaEn: 'Fresh squid in a thick garlic fish-sauce glaze',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Mực ống tươi, tỏi, ớt, nước mắm, đường thốt nốt, tiêu, hành lá.',
    nguyenLieuEn: 'Fresh squid, garlic, chilli, fish sauce, palm sugar, pepper, spring onion.',
    cheBien: 'Mực chiên nhanh ở lửa lớn cho săn rồi mới rưới sốt mắm tỏi đã thắng sánh, đảo vài lượt là tắt bếp để mực không dai.',
    cheBienEn: 'The squid is flash-fried over high heat, then tossed briefly in a reduced garlic fish-sauce glaze so it does not turn rubbery.',
    luuY: 'Món mặn đậm, hợp ăn với cơm trắng. Có hải sản, khách dị ứng báo trước.',
    luuYEn: 'Deliberately salty and meant to be eaten with plain rice. Contains shellfish — please tell us about allergies.',
    tim: 'fried squid Vietnamese',
  },
  {
    slug: 'so-diep-nuong-mo-hanh', dm: 'khaivi', gia: 245000, phut: 20,
    ten: 'Sò điệp nướng mỡ hành', tenEn: 'Grilled scallops with scallion oil',
    mota: 'Sò điệp nguyên vỏ, đậu phộng rang',
    motaEn: 'Scallops in the shell with roasted peanuts',
    phan: 'Phần 6 con', phanEn: '6 pieces',
    nguyenLieu: 'Sò điệp tươi nguyên vỏ, mỡ hành, đậu phộng rang giã, muối tiêu chanh.',
    nguyenLieuEn: 'Fresh scallops in the shell, scallion oil, crushed roasted peanuts, salt-pepper-lime dip.',
    cheBien: 'Sò nướng nguyên vỏ trên than để giữ nước ngọt, chan mỡ hành và rắc đậu phộng ngay khi vừa mở miệng.',
    cheBienEn: 'Grilled in the shell over charcoal so the juices stay in, then finished with scallion oil and peanuts the moment the shells open.',
    luuY: 'Giá theo hàng tươi trong ngày nên có thể chênh so với bảng giá. Có hải sản và đậu phộng.',
    luuYEn: 'Priced on the day market rate, so it may differ from the listed figure. Contains shellfish and peanuts.',
    tim: 'grilled scallop',
  },
  {
    slug: 'ca-tim-nuong-mo-hanh', dm: 'khaivi', gia: 95000, phut: 20,
    ten: 'Cà tím nướng mỡ hành', tenEn: 'Grilled aubergine with scallion oil',
    mota: 'Món chay, cà tím nướng than nguyên trái',
    motaEn: 'Vegetarian, whole aubergine grilled over charcoal',
    phan: 'Phần 2-3 người', phanEn: 'Serves 2-3',
    nguyenLieu: 'Cà tím, hành lá, dầu ăn, đậu phộng rang, nước mắm chay hoặc nước tương.',
    nguyenLieuEn: 'Aubergine, spring onion, oil, roasted peanuts, vegetarian fish sauce or soy sauce.',
    cheBien: 'Cà tím nướng nguyên trái trên than đến khi vỏ cháy xém, bóc vỏ rồi xé dọc thớ, chan mỡ hành lúc còn nóng.',
    cheBienEn: 'The whole aubergine is grilled over charcoal until the skin blackens, then peeled and torn along the grain, with scallion oil poured over while still hot.',
    luuY: 'Món chay hoàn toàn nếu dùng nước tương, báo trước khi gọi. Có đậu phộng.',
    luuYEn: 'Fully vegetarian when served with soy sauce — say so when ordering. Contains peanuts.',
    tim: 'grilled eggplant Vietnamese',
  },
  {
    slug: 'dau-hu-chien-sa-ot', dm: 'khaivi', gia: 75000, phut: 15,
    ten: 'Đậu hũ chiên sả ớt', tenEn: 'Tofu fried with lemongrass and chilli',
    mota: 'Món chay, đậu hũ non chiên giòn rìa',
    motaEn: 'Vegetarian, silken tofu fried crisp at the edges',
    phan: 'Phần 2-3 người', phanEn: 'Serves 2-3',
    nguyenLieu: 'Đậu hũ non, sả băm, ớt, nước tương, đường, tiêu, hành lá.',
    nguyenLieuEn: 'Silken tofu, minced lemongrass, chilli, soy sauce, sugar, pepper, spring onion.',
    cheBien: 'Đậu hũ để ráo thật kỹ rồi mới chiên, nếu còn ướt dầu sẽ bắn và rìa không giòn. Sả băm phi riêng cho vàng rồi mới trộn vào.',
    cheBienEn: 'The tofu is drained thoroughly before frying — still wet, the oil spits and the edges will not crisp. The lemongrass is fried separately until golden, then folded in.',
    luuY: 'Món chay hoàn toàn. Cay vừa, bên mình làm không cay nếu khách báo trước.',
    luuYEn: 'Fully vegetarian. Mildly spicy; we can leave out the chilli if you say so in advance.',
    tim: 'fried tofu lemongrass',
  },
  {
    slug: 'nom-hoa-chuoi', dm: 'khaivi', gia: 105000, phut: 20,
    ten: 'Nộm hoa chuối', tenEn: 'Banana blossom salad',
    mota: 'Hoa chuối bào, lạc rang, rau thơm',
    motaEn: 'Shaved banana blossom with roasted peanuts and herbs',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Hoa chuối, cà rốt, rau kinh giới, lạc rang, hành phi, nước mắm chua ngọt.',
    nguyenLieuEn: 'Banana blossom, carrot, Vietnamese balm, roasted peanuts, fried shallots, sweet-and-sour fish sauce.',
    cheBien: 'Hoa chuối bào xong thả ngay vào nước chanh loãng cho khỏi thâm, vắt ráo rồi trộn. Rắc lạc và hành phi sau cùng để giữ độ giòn.',
    cheBienEn: 'The blossom goes straight into weak lemon water after shaving so it does not darken, then is squeezed dry and dressed. Peanuts and shallots go on last to stay crisp.',
    luuY: 'Hoa chuối có vị chát nhẹ, đó là đặc trưng của món. Có lạc, khách dị ứng báo trước.',
    luuYEn: 'Banana blossom carries a faint astringency, which is characteristic of the dish. Contains peanuts — please tell us about allergies.',
    tim: 'banana blossom salad',
  },
  {
    slug: 'ngheu-hap-sa', dm: 'khaivi', gia: 145000, phut: 15,
    ten: 'Nghêu hấp sả', tenEn: 'Clams steamed with lemongrass',
    mota: 'Nghêu Cần Giờ, nước dùng ngọt tự nhiên',
    motaEn: 'Can Gio clams in their own sweet broth',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Nghêu Cần Giờ, sả đập dập, lá chanh, ớt, rau răm, muối tiêu chanh.',
    nguyenLieuEn: 'Can Gio clams, bruised lemongrass, kaffir lime leaf, chilli, Vietnamese coriander, salt-pepper-lime dip.',
    cheBien: 'Nghêu ngâm nước vo gạo cho nhả cát, hấp cùng sả đến khi vừa mở miệng là bắc ra, hấp quá thì thịt teo lại.',
    cheBienEn: 'The clams soak in rice-washing water to purge sand, then steam with lemongrass only until they open; any longer and the meat shrinks.',
    luuY: 'Có hải sản, khách dị ứng báo trước. Nghêu theo con nước nên có ngày hết hàng, bên mình sẽ báo khi nhận đặt.',
    luuYEn: 'Contains shellfish — please tell us about allergies. Clams follow the tides and some days sell out; we will say so when you book.',
    tim: 'steamed clams lemongrass',
  },
  {
    slug: 'khoai-lang-ken-chien', dm: 'khaivi', gia: 65000, phut: 15,
    ten: 'Khoai lang kén chiên', tenEn: 'Fried sweet potato croquettes',
    mota: 'Món chay, ngoài giòn trong dẻo',
    motaEn: 'Vegetarian, crisp outside and chewy within',
    phan: 'Phần 12 viên', phanEn: '12 pieces',
    nguyenLieu: 'Khoai lang mật, bột năng, nước cốt dừa, đường, mè trắng.',
    nguyenLieuEn: 'Honey sweet potato, tapioca starch, coconut milk, sugar, white sesame.',
    cheBien: 'Khoai hấp chín tán nhuyễn trộn bột năng, nặn hình thoi rồi chiên hai lửa: lửa nhỏ cho chín trong, lửa lớn cho giòn ngoài.',
    cheBienEn: 'The sweet potato is steamed, mashed with tapioca starch, shaped into diamonds and fried twice: low heat to cook through, high heat to crisp the shell.',
    luuY: 'Món chay hoàn toàn. Ăn nóng mới ngon, để nguội sẽ cứng lại.',
    luuYEn: 'Fully vegetarian. Best eaten hot; they harden as they cool.',
    tim: 'fried sweet potato',
  },
];
