// Hai mươi món lẩu và nướng.
module.exports = [
  {
    slug: 'lau-thai-hai-san', dm: 'lau', gia: 545000, phut: 30,
    ten: 'Lẩu Thái hải sản', tenEn: 'Thai-style seafood hotpot',
    mota: 'Chua cay, tôm mực nghêu và nấm',
    motaEn: 'Hot and sour with prawn, squid, clams and mushrooms',
    phan: 'Nồi 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Tôm, mực, nghêu, nấm rơm, sả, riềng, lá chanh, ớt, cà chua, bún tươi.',
    nguyenLieuEn: 'Prawn, squid, clams, straw mushroom, lemongrass, galangal, kaffir lime leaf, chilli, tomato, fresh vermicelli.',
    cheBien: 'Nước dùng nấu từ xương và đầu tôm, dậy mùi bằng sả riềng lá chanh đập dập chứ không dùng gói gia vị pha sẵn.',
    cheBienEn: 'The broth is built on bones and prawn heads, lifted with bruised lemongrass, galangal and lime leaf rather than a packet mix.',
    luuY: 'Món cay, độ cay điều chỉnh được nếu báo trước. Có hải sản, khách dị ứng báo trước.',
    luuYEn: 'Spicy, and the heat can be adjusted on request. Contains shellfish — please tell us about allergies.',
    tim: 'tom yum seafood hotpot',
  },
  {
    slug: 'lau-bo-nhung-dam', dm: 'lau', gia: 595000, phut: 25,
    ten: 'Lẩu bò nhúng dấm', tenEn: 'Beef hotpot with vinegar broth',
    mota: 'Bò tơ thái mỏng, nhúng nước dấm dừa',
    motaEn: 'Thinly sliced young beef dipped in coconut vinegar broth',
    phan: 'Nồi 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Bò tơ thái mỏng, dấm dừa, nước dừa, hành tây, sả, bánh tráng, rau sống, mắm nêm.',
    nguyenLieuEn: 'Thinly sliced young beef, coconut vinegar, coconut water, onion, lemongrass, rice paper, garden herbs, fermented anchovy sauce.',
    cheBien: 'Nước nhúng pha dấm dừa với nước dừa tươi cho chua thanh. Bò thái mỏng nhúng vài giây là chín, để lâu sẽ dai.',
    cheBienEn: 'The dipping broth balances coconut vinegar with fresh coconut water for a clean sourness. The beef is sliced thin and needs only seconds; longer and it toughens.',
    luuY: 'Mắm nêm mùi đậm, bên mình có nước mắm thay thế. Bò nhúng tái, khách muốn chín kỹ nhúng lâu hơn.',
    luuYEn: 'The anchovy sauce is pungent; fish sauce is available instead. The beef is meant to be rare — dip it longer if you prefer it cooked through.',
    tim: 'beef hotpot Vietnamese',
  },
  {
    slug: 'lau-ca-bop-la-giang', dm: 'lau', gia: 565000, phut: 30,
    ten: 'Lẩu cá bớp lá giang', tenEn: 'Cobia hotpot with giang leaf',
    mota: 'Cá bớp cắt khúc, chua thanh lá giang',
    motaEn: 'Cobia steaks in a clean giang-leaf sourness',
    phan: 'Nồi 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Cá bớp, lá giang, măng chua, cà chua, ớt, rau muống, bún tươi.',
    nguyenLieuEn: 'Cobia, giang leaf, pickled bamboo shoot, tomato, chilli, water spinach, fresh vermicelli.',
    cheBien: 'Lá giang vò nhẹ rồi thả vào nồi, không đun sôi lâu vì lá nấu quá sẽ chuyển sang đắng thay vì chua.',
    cheBienEn: 'The giang leaf is lightly crushed and dropped in, never boiled long — overcooked it turns bitter instead of sour.',
    luuY: 'Cá bớp có xương sống lớn, dễ gỡ. Món chua, khách đau dạ dày nên cân nhắc.',
    luuYEn: 'Cobia has a large central bone that lifts out easily. The broth is sour and may not suit a sensitive stomach.',
    tim: 'fish hotpot Vietnamese',
  },
  {
    slug: 'lau-riu-rieu-cua-dong', dm: 'lau', gia: 485000, phut: 35,
    ten: 'Lẩu riêu cua đồng', tenEn: 'Field crab hotpot',
    mota: 'Riêu cua đồng giã tay, đậu rán và cà chua',
    motaEn: 'Hand-pounded field crab with fried tofu and tomato',
    phan: 'Nồi 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Cua đồng giã lọc, đậu phụ rán, cà chua, dấm bỗng, hành lá, rau sống, bún tươi.',
    nguyenLieuEn: 'Pounded and strained field crab, fried tofu, tomato, fermented rice vinegar, spring onion, garden herbs, fresh vermicelli.',
    cheBien: 'Cua giã tay lọc lấy nước rồi đun lửa vừa cho riêu nổi thành tảng. Khuấy mạnh lúc này thì riêu vỡ vụn, không đóng bánh được.',
    cheBienEn: 'The crab is pounded, strained and heated gently so the protein rises in soft cakes. Stir hard at this point and it breaks into crumbs.',
    luuY: 'Có hải sản nước ngọt. Nồi nhỏ nhất phục vụ bốn người, không tách phần lẻ.',
    luuYEn: 'Contains freshwater shellfish. The smallest pot serves four and cannot be split further.',
    tim: 'crab noodle soup Vietnamese bun rieu',
  },
  {
    slug: 'lau-de-tiem-thuoc-bac', dm: 'lau', gia: 625000, phut: 45,
    ten: 'Lẩu dê tiềm thuốc bắc', tenEn: 'Goat hotpot with Chinese herbs',
    mota: 'Dê hầm thuốc bắc, khoai môn và tàu hũ ky',
    motaEn: 'Goat stewed with herbs, taro and tofu skin',
    phan: 'Nồi 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Thịt dê, thuốc bắc, khoai môn, tàu hũ ky, chao, rau tần ô, mì tươi.',
    nguyenLieuEn: 'Goat meat, Chinese herbs, taro, tofu skin, fermented bean curd, garland chrysanthemum, fresh noodles.',
    cheBien: 'Dê hầm cùng thuốc bắc bốn mươi lăm phút cho mềm và bớt mùi. Khoai môn cho vào sau để không tan vào nước.',
    cheBienEn: 'The goat stews with the herb mix for forty-five minutes to tenderise and tame its aroma. The taro goes in later so it does not dissolve.',
    luuY: 'Hầm lâu nên bắt buộc đặt trước. Thịt dê có mùi đặc trưng dù đã khử.',
    luuYEn: 'The long stew means it must be ordered ahead. Goat keeps a distinctive aroma even after the herbs.',
    tim: 'goat hotpot herbal',
  },
  {
    slug: 'lau-nam-chay', dm: 'lau', gia: 385000, phut: 25,
    ten: 'Lẩu nấm chay', tenEn: 'Vegetarian mushroom hotpot',
    mota: 'Món chay, tám loại nấm và rau củ',
    motaEn: 'Vegetarian, eight kinds of mushroom with vegetables',
    phan: 'Nồi 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Nấm đùi gà, nấm kim châm, nấm đông cô, nấm bào ngư, nấm rơm, củ sen, bắp non, tàu hũ non, mì tươi.',
    nguyenLieuEn: 'King oyster, enoki, shiitake, oyster, straw mushroom, lotus root, baby corn, silken tofu, fresh noodles.',
    cheBien: 'Nước dùng ninh từ củ sen, bắp và nấm đông cô khô trong hai tiếng, ngọt tự nhiên không dùng bột nêm.',
    cheBienEn: 'The broth simmers two hours from lotus root, corn and dried shiitake, sweet on its own without stock powder.',
    luuY: 'Món chay hoàn toàn. Nấm kim châm dễ chín, nhúng lâu sẽ nhũn.',
    luuYEn: 'Fully vegetarian. Enoki cooks in moments and goes limp if left in the pot.',
    tim: 'mushroom hotpot vegetarian',
  },
  {
    slug: 'lau-hai-san-chua-cay', dm: 'lau', gia: 575000, phut: 30,
    ten: 'Lẩu hải sản chua cay', tenEn: 'Hot and sour seafood hotpot',
    mota: 'Tôm, mực, cá phi lê, nước dùng me',
    motaEn: 'Prawn, squid and fish fillet in a tamarind broth',
    phan: 'Nồi 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Tôm, mực, cá phi lê, nghêu, me chín, dứa, cà chua, ớt, rau muống, bún tươi.',
    nguyenLieuEn: 'Prawn, squid, fish fillet, clams, ripe tamarind, pineapple, tomato, chilli, water spinach, fresh vermicelli.',
    cheBien: 'Nước dùng nấu từ đầu tôm và xương cá, chua bằng me chín dầm. Hải sản để riêng đĩa, khách nhúng tới đâu chín tới đó.',
    cheBienEn: 'The broth is built on prawn heads and fish bones and soured with mashed ripe tamarind. The seafood comes on a separate plate to be dipped as you go.',
    luuY: 'Có hải sản. Món cay và chua, khách đau dạ dày nên cân nhắc.',
    luuYEn: 'Contains shellfish. Hot and sour, and may not suit a sensitive stomach.',
    tim: 'seafood hotpot',
  },
  {
    slug: 'lau-vit-nau-chao', dm: 'lau', gia: 465000, phut: 40,
    ten: 'Lẩu vịt nấu chao', tenEn: 'Duck hotpot with fermented bean curd',
    mota: 'Vịt xiêm, chao đỏ, khoai môn',
    motaEn: 'Muscovy duck with red fermented bean curd and taro',
    phan: 'Nồi 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Vịt xiêm, chao đỏ, khoai môn, nước dừa, sả, rau muống, bún tươi.',
    nguyenLieuEn: 'Muscovy duck, red fermented bean curd, taro, coconut water, lemongrass, water spinach, fresh vermicelli.',
    cheBien: 'Vịt ướp chao và sả một tiếng rồi hầm nước dừa. Khoai môn chiên sơ trước khi thả vào để giữ hình mà vẫn bở.',
    cheBienEn: 'The duck marinates an hour in fermented bean curd and lemongrass, then stews in coconut water. The taro is lightly fried first so it holds its shape while staying floury.',
    luuY: 'Chao có mùi đậm, khách chưa quen nên cân nhắc. Hầm lâu nên đặt trước.',
    luuYEn: 'Fermented bean curd has a strong aroma; think twice if it is new to you. The long stew means ordering ahead.',
    tim: 'duck hotpot Vietnamese',
  },
  {
    slug: 'lau-ca-hoi-mang-chua', dm: 'lau', gia: 655000, phut: 30,
    ten: 'Lẩu cá hồi măng chua', tenEn: 'Salmon hotpot with pickled bamboo',
    mota: 'Đầu và xương cá hồi, măng chua tự muối',
    motaEn: 'Salmon head and bones with house-pickled bamboo',
    phan: 'Nồi 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Đầu và xương cá hồi, phi lê cá hồi, măng chua, cà chua, thì là, hành lá, bún tươi.',
    nguyenLieuEn: 'Salmon head and bones, salmon fillet, pickled bamboo shoot, tomato, dill, spring onion, fresh vermicelli.',
    cheBien: 'Đầu và xương cá nướng sơ trước khi ninh để nước dùng thơm mà không tanh. Phi lê để riêng, nhúng khi ăn.',
    cheBienEn: 'The head and bones are roasted before simmering so the broth smells sweet rather than fishy. The fillet is kept separate and dipped as you eat.',
    luuY: 'Có hải sản. Măng chua tự muối nên độ chua thay đổi theo mẻ.',
    luuYEn: 'Contains fish. The bamboo is pickled in house, so the sourness varies a little between batches.',
    tim: 'salmon hotpot',
  },
  {
    slug: 'lau-ech-mang-cay', dm: 'lau', gia: 495000, phut: 30,
    ten: 'Lẩu ếch măng cay', tenEn: 'Frog hotpot with bamboo and chilli',
    mota: 'Ếch đồng, măng tươi, cay nồng',
    motaEn: 'Field frog with fresh bamboo, distinctly hot',
    phan: 'Nồi 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Ếch đồng, măng tươi, ớt hiểm, sa tế, rau muống, tía tô, bún tươi.',
    nguyenLieuEn: 'Field frog, fresh bamboo shoot, bird chilli, chilli oil, water spinach, perilla, fresh vermicelli.',
    cheBien: 'Ếch ướp sa tế rồi xào săn trước khi cho nước vào, cách này giữ thịt ếch chắc thay vì bở ra trong nồi.',
    cheBienEn: 'The frog is tossed in chilli oil and seared before the broth goes in, which keeps the meat firm instead of falling apart in the pot.',
    luuY: 'Món rất cay, độ cay điều chỉnh được nếu báo trước. Thịt ếch nhiều xương nhỏ.',
    luuYEn: 'Very spicy, and the heat can be adjusted on request. Frog has many small bones.',
    tim: 'frog hotpot',
  },
  {
    slug: 'suon-nuong-bbq', dm: 'lau', gia: 385000, phut: 40,
    ten: 'Sườn nướng BBQ mật ong', tenEn: 'Honey BBQ pork ribs',
    mota: 'Sườn cây nướng chậm, phết mật ong',
    motaEn: 'Rib racks slow-grilled and brushed with honey',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Sườn cây heo, mật ong, xì dầu, tỏi, ớt bột, tiêu, khoai tây chiên.',
    nguyenLieuEn: 'Pork rib rack, honey, soy sauce, garlic, chilli powder, pepper, fried potato.',
    cheBien: 'Sườn ướp qua đêm, nướng chậm ở lửa nhỏ bốn mươi phút rồi mới phết mật ong ở mười phút cuối để lớp áo bóng mà không cháy khét.',
    cheBienEn: 'The ribs marinate overnight and grill slowly for forty minutes, with the honey brushed on only in the last ten so the glaze shines instead of scorching.',
    luuY: 'Nướng chậm nên đặt trước. Món ngọt đậm, trẻ nhỏ thường thích.',
    luuYEn: 'Slow-grilled, so please order ahead. Sweet and rich, usually a hit with children.',
    tim: 'bbq pork ribs honey',
  },
  {
    slug: 'ba-chi-nuong-sa', dm: 'lau', gia: 265000, phut: 25,
    ten: 'Ba chỉ nướng sả', tenEn: 'Grilled pork belly with lemongrass',
    mota: 'Ba chỉ thái dày, nướng vỉ tại bàn',
    motaEn: 'Thick-cut pork belly grilled at your table',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Ba chỉ heo, sả băm, tỏi, mật ong, nước mắm, rau sống, bánh tráng, mắm nêm.',
    nguyenLieuEn: 'Pork belly, minced lemongrass, garlic, honey, fish sauce, garden herbs, rice paper, fermented anchovy sauce.',
    cheBien: 'Ba chỉ thái dày một phân, ướp sả tỏi bốn tiếng. Nướng vỉ tại bàn để khách canh độ chín theo ý mình.',
    cheBienEn: 'The belly is cut a centimetre thick and marinates four hours in lemongrass and garlic, then grills at your table so you judge the doneness.',
    luuY: 'Bếp nướng đặt tại bàn, không bố trí được ở phòng máy lạnh kín. Món nhiều mỡ.',
    luuYEn: 'The grill sits on the table and cannot be set up in a sealed air-conditioned room. A fatty dish.',
    tim: 'grilled pork belly',
  },
  {
    slug: 'muc-nuong-sa-te', dm: 'lau', gia: 325000, phut: 20,
    ten: 'Mực nướng sa tế', tenEn: 'Grilled squid with chilli oil',
    mota: 'Mực ống nguyên con, nướng than',
    motaEn: 'Whole squid tubes over charcoal',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Mực ống tươi, sa tế, sả, tỏi, muối tiêu chanh, rau răm.',
    nguyenLieuEn: 'Fresh squid tubes, chilli oil, lemongrass, garlic, salt-pepper-lime dip, Vietnamese coriander.',
    cheBien: 'Mực khứa chéo thân rồi nướng nhanh ở lửa lớn, nướng quá tay thì mực co lại và dai như cao su.',
    cheBienEn: 'The tubes are scored on the diagonal and grilled fast over high heat; overdone, squid shrinks and turns rubbery.',
    luuY: 'Có hải sản. Món cay, làm không cay được nếu báo trước.',
    luuYEn: 'Contains shellfish. Spicy, and can be made without chilli on request.',
    tim: 'grilled squid charcoal',
  },
  {
    slug: 'ca-nuc-nuong-giay-bac', dm: 'lau', gia: 215000, phut: 25,
    ten: 'Cá nục nướng giấy bạc', tenEn: 'Mackerel grilled in foil',
    mota: 'Cá nục tươi, hành tây và ớt chuông',
    motaEn: 'Fresh mackerel with onion and bell pepper',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Cá nục tươi, hành tây, ớt chuông, sả, nghệ, bơ, chanh.',
    nguyenLieuEn: 'Fresh mackerel, onion, bell pepper, lemongrass, turmeric, butter, lime.',
    cheBien: 'Cá gói giấy bạc cùng rau củ rồi nướng than, hơi nước giữ lại bên trong nên thịt cá mềm chứ không khô như nướng trần.',
    cheBienEn: 'The fish is sealed in foil with the vegetables and grilled over charcoal; the trapped steam keeps the flesh moist instead of drying as it would on an open grill.',
    luuY: 'Cá nục nhiều xương dăm, cẩn thận với trẻ nhỏ.',
    luuYEn: 'Mackerel has many fine bones; take care with small children.',
    tim: 'fish grilled foil',
  },
  {
    slug: 'ga-nuong-lu', dm: 'lau', gia: 395000, phut: 45,
    ten: 'Gà nướng lu', tenEn: 'Chicken roasted in a clay urn',
    mota: 'Treo trong lu đất, da giòn đều',
    motaEn: 'Hung inside a clay urn for evenly crisp skin',
    phan: 'Nguyên con, 4-6 người', phanEn: 'Whole bird, serves 4-6',
    nguyenLieu: 'Gà ta nguyên con, ngũ vị hương, mật ong, sả, muối hột, lá chanh.',
    nguyenLieuEn: 'Whole free-range chicken, five-spice, honey, lemongrass, coarse salt, kaffir lime leaf.',
    cheBien: 'Gà treo trong lu đất kín, chín bằng hơi nóng phản xạ từ thành lu nên da vàng đều mọi mặt mà không cần trở.',
    cheBienEn: 'The bird hangs inside a sealed clay urn and cooks by heat reflected from the walls, so the skin browns evenly without turning.',
    luuY: 'Nướng lu mất bốn mươi lăm phút, bắt buộc đặt trước một buổi.',
    luuYEn: 'Urn roasting takes forty-five minutes and must be ordered one session ahead.',
    tim: 'roast chicken clay oven',
  },
  {
    slug: 'bo-bit-tet-tieu-den', dm: 'lau', gia: 425000, phut: 20,
    ten: 'Bò bít tết tiêu đen', tenEn: 'Beef steak with black pepper',
    mota: 'Thăn ngoại áp chảo, sốt tiêu đen',
    motaEn: 'Pan-seared sirloin in black pepper sauce',
    phan: 'Phần 1-2 người', phanEn: 'Serves 1-2',
    nguyenLieu: 'Thăn ngoại bò, tiêu đen xay thô, bơ, tỏi, khoai tây nghiền, rau củ áp chảo.',
    nguyenLieuEn: 'Beef sirloin, coarsely ground black pepper, butter, garlic, mashed potato, pan-seared vegetables.',
    cheBien: 'Thịt để về nhiệt độ phòng trước khi áp chảo, nghỉ năm phút sau khi chín để nước thịt phân bố đều chứ không chảy hết ra đĩa.',
    cheBienEn: 'The steak comes to room temperature before searing and rests five minutes afterwards so the juices settle instead of running onto the plate.',
    luuY: 'Bên mình làm chín vừa theo mặc định, khách muốn độ chín khác báo trước khi gọi.',
    luuYEn: 'Cooked medium by default; tell us when ordering if you would like it otherwise.',
    tim: 'beef steak black pepper',
  },
  {
    slug: 'tom-hum-nuong-pho-mai', dm: 'lau', gia: 1250000, phut: 30,
    ten: 'Tôm hùm nướng phô mai', tenEn: 'Lobster grilled with cheese',
    mota: 'Tôm hùm xanh, phô mai mozzarella',
    motaEn: 'Green lobster with mozzarella',
    phan: 'Phần 2-3 người', phanEn: 'Serves 2-3',
    nguyenLieu: 'Tôm hùm xanh, phô mai mozzarella, bơ tỏi, tiêu, chanh, rau củ nướng.',
    nguyenLieuEn: 'Green lobster, mozzarella, garlic butter, pepper, lime, grilled vegetables.',
    cheBien: 'Tôm bổ đôi, phết bơ tỏi rồi nướng tới khi thịt vừa đục, phủ phô mai và nướng thêm ba phút cho vàng mặt.',
    cheBienEn: 'The lobster is halved, brushed with garlic butter and grilled until the flesh turns opaque, then topped with cheese and given three more minutes to brown.',
    luuY: 'Giá theo tôm sống trong bể, tính theo cân thực tế. Có hải sản và sữa.',
    luuYEn: 'Priced from the live tank and billed by actual weight. Contains shellfish and dairy.',
    tim: 'grilled lobster cheese',
  },
  {
    slug: 'hau-nuong-mo-hanh', dm: 'lau', gia: 235000, phut: 20,
    ten: 'Hàu nướng mỡ hành', tenEn: 'Grilled oysters with scallion oil',
    mota: 'Hàu sữa nguyên vỏ, đậu phộng rang',
    motaEn: 'Milk oysters in the shell with roasted peanuts',
    phan: 'Phần 12 con', phanEn: '12 pieces',
    nguyenLieu: 'Hàu sữa, mỡ hành, đậu phộng rang giã, hành phi, muối tiêu chanh.',
    nguyenLieuEn: 'Milk oysters, scallion oil, crushed roasted peanuts, fried shallots, salt-pepper-lime dip.',
    cheBien: 'Hàu tách vỏ giữ nguyên nước, nướng than chừng ba phút rồi chan mỡ hành, không nướng lâu vì hàu sẽ teo lại.',
    cheBienEn: 'The oysters are shucked with their liquor kept, grilled about three minutes and finished with scallion oil; longer and they shrink away.',
    luuY: 'Có hải sản và đậu phộng. Hàu theo con nước, có ngày hết hàng.',
    luuYEn: 'Contains shellfish and peanuts. Oysters follow the tides and some days sell out.',
    tim: 'grilled oyster',
  },
  {
    slug: 'nam-nuong-sa-te', dm: 'lau', gia: 145000, phut: 20,
    ten: 'Nấm nướng sa tế', tenEn: 'Grilled mushrooms with chilli oil',
    mota: 'Món chay, nấm đùi gà và bào ngư',
    motaEn: 'Vegetarian, king oyster and oyster mushrooms',
    phan: 'Phần 2-3 người', phanEn: 'Serves 2-3',
    nguyenLieu: 'Nấm đùi gà, nấm bào ngư, sa tế chay, sả, dầu ăn, muối tiêu chanh.',
    nguyenLieuEn: 'King oyster mushroom, oyster mushroom, vegetarian chilli oil, lemongrass, oil, salt-pepper-lime dip.',
    cheBien: 'Nấm cắt dày rồi nướng vỉ cho xém cạnh, phết sa tế ở cuối để ớt không cháy đắng trên than.',
    cheBienEn: 'The mushrooms are cut thick and grilled until the edges char, with the chilli oil brushed on at the end so it does not burn bitter over the coals.',
    luuY: 'Món chay hoàn toàn nếu dùng sa tế chay, báo trước khi gọi. Món cay.',
    luuYEn: 'Fully vegetarian when made with vegetarian chilli oil — say so when ordering. Spicy.',
    tim: 'grilled mushroom skewer',
  },
  {
    slug: 'combo-lau-nuong-gia-dinh', dm: 'lau', gia: 890000, phut: 35,
    ten: 'Combo lẩu nướng gia đình', tenEn: 'Family hotpot and grill set',
    mota: 'Một nồi lẩu và tám món nướng, cho 6 người',
    motaEn: 'One hotpot plus eight grill items, for six people',
    phan: 'Phần 6-8 người', phanEn: 'Serves 6-8',
    nguyenLieu: 'Nồi lẩu chua cay, bò, ba chỉ, tôm, mực, nấm, bắp, rau nhúng, bún tươi.',
    nguyenLieuEn: 'Hot-and-sour hotpot, beef, pork belly, prawn, squid, mushroom, corn, dipping greens, fresh vermicelli.',
    cheBien: 'Bố trí bếp lẩu và vỉ nướng cùng lúc trên một bàn, đồ nướng ướp sẵn từ bếp để khách chỉ việc đặt lên vỉ.',
    cheBienEn: 'A hotpot burner and a grill are set up side by side on one table, with everything pre-marinated in the kitchen so you only have to lay it on.',
    luuY: 'Cần bàn rộng và khu vực thoáng khói, không bố trí được ở phòng máy lạnh kín. Có hải sản.',
    luuYEn: 'Needs a large table and a well-ventilated area; cannot be set up in a sealed air-conditioned room. Contains shellfish.',
    tim: 'hotpot barbecue table',
  },
];
