// Món chính, đợt hai: mười lăm món hải sản, gà vịt và món chay.
module.exports = [
  {
    slug: 'tom-su-hap-nuoc-dua', dm: 'chinh', gia: 485000, phut: 20,
    ten: 'Tôm sú hấp nước dừa', tenEn: 'Tiger prawns steamed in coconut water',
    mota: 'Hấp trong trái dừa, giữ nguyên vị ngọt',
    motaEn: 'Steamed inside the coconut to keep the sweetness',
    phan: 'Phần 8 con lớn', phanEn: '8 large prawns',
    nguyenLieu: 'Tôm sú, nước dừa xiêm, sả, lá chanh, muối tiêu chanh, rau răm.',
    nguyenLieuEn: 'Tiger prawn, young coconut water, lemongrass, kaffir lime leaf, salt-pepper-lime dip, Vietnamese coriander.',
    cheBien: 'Tôm hấp trong nước dừa cùng sả và lá chanh, canh đúng lúc vỏ vừa chuyển đỏ là bắc ra, hấp quá thì thịt bở.',
    cheBienEn: 'The prawns steam in coconut water with lemongrass and lime leaf, and come off the heat the moment the shells turn red; any longer and the flesh goes mealy.',
    luuY: 'Giá theo tôm tươi trong ngày nên có thể chênh so với bảng giá. Có hải sản.',
    luuYEn: 'Priced on the day market rate for live prawns, so it may differ from the listed figure. Contains shellfish.',
    tim: 'steamed prawns coconut',
  },
  {
    slug: 'cua-rang-me', dm: 'chinh', gia: 650000, phut: 30,
    ten: 'Cua rang me', tenEn: 'Crab in tamarind sauce',
    mota: 'Cua thịt Cà Mau, sốt me chua ngọt',
    motaEn: 'Ca Mau mud crab in a sweet-sour tamarind glaze',
    phan: 'Phần 2-3 người', phanEn: 'Serves 2-3',
    nguyenLieu: 'Cua thịt Cà Mau, me chín, đường thốt nốt, tỏi, ớt, hành tây, bánh mì ăn kèm.',
    nguyenLieuEn: 'Ca Mau mud crab, ripe tamarind, palm sugar, garlic, chilli, onion, baguette on the side.',
    cheBien: 'Cua chiên sơ cho săn rồi rang với sốt me thắng sánh. Sốt phải đủ đặc để bám vào mai chứ không chảy xuống đáy đĩa.',
    cheBienEn: 'The crab is flash-fried to firm the meat, then tossed in a reduced tamarind glaze thick enough to cling to the shell rather than pool on the plate.',
    luuY: 'Giá theo cân cua tươi trong ngày. Ăn cua cần dùng tay và kẹp, bên mình dọn kèm khăn và chén nước chanh.',
    luuYEn: 'Priced by the weight of live crab on the day. Eating it means hands and crackers, so we bring a towel and a lemon bowl.',
    tim: 'tamarind crab',
  },
  {
    slug: 'ca-hap-hong-kong', dm: 'chinh', gia: 560000, phut: 30,
    ten: 'Cá chẽm hấp Hồng Kông', tenEn: 'Hong Kong style steamed sea bass',
    mota: 'Cá chẽm nguyên con, xì dầu và gừng hành',
    motaEn: 'Whole sea bass with soy, ginger and spring onion',
    phan: 'Phần 4-6 người', phanEn: 'Serves 4-6',
    nguyenLieu: 'Cá chẽm nguyên con, gừng, hành lá, xì dầu, dầu mè, nấm đông cô, cải bẹ xanh.',
    nguyenLieuEn: 'Whole sea bass, ginger, spring onion, soy sauce, sesame oil, shiitake mushroom, mustard greens.',
    cheBien: 'Cá hấp đúng mười hai phút, rưới xì dầu nóng và dầu mè sôi lên gừng hành thái sợi để dậy mùi ngay tại bàn.',
    cheBienEn: 'The fish steams for exactly twelve minutes, then hot soy and smoking sesame oil are poured over shredded ginger and spring onion so the aroma lifts at the table.',
    luuY: 'Cá tươi sống chọn trong bể, giá theo cân thực tế. Cá có xương.',
    luuYEn: 'The fish is chosen live from the tank and billed by actual weight. It has bones.',
    tim: 'steamed sea bass Chinese style',
  },
  {
    slug: 'muc-nhoi-thit-hap', dm: 'chinh', gia: 315000, phut: 30,
    ten: 'Mực nhồi thịt hấp', tenEn: 'Steamed squid stuffed with pork',
    mota: 'Mực ống nhồi thịt bằm, nấm mèo',
    motaEn: 'Squid tubes stuffed with minced pork and wood-ear',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Mực ống, thịt bằm, nấm mèo, miến, hành tím, tiêu, nước mắm gừng.',
    nguyenLieuEn: 'Squid tubes, minced pork, wood-ear mushroom, glass noodles, shallot, pepper, ginger fish sauce.',
    cheBien: 'Nhồi nhân vừa tay, chừa chỗ cho nhân nở, xăm vài lỗ trên thân mực để hơi thoát ra chứ không làm nứt mực khi hấp.',
    cheBienEn: 'The tubes are filled loosely to leave room for the stuffing to swell, and pricked a few times so steam escapes instead of splitting the squid.',
    luuY: 'Có hải sản. Hấp mất ba mươi phút nên đặt trước.',
    luuYEn: 'Contains shellfish. Thirty minutes to steam, so please order ahead.',
    tim: 'stuffed squid',
  },
  {
    slug: 'ech-xao-lan', dm: 'chinh', gia: 295000, phut: 25,
    ten: 'Ếch xào lăn', tenEn: 'Frog sautéed in coconut curry',
    mota: 'Ếch đồng, nước cốt dừa, cà ri và sả',
    motaEn: 'Field frog with coconut milk, curry and lemongrass',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Ếch đồng, nước cốt dừa, bột cà ri, sả băm, đậu phộng rang, rau răm, bánh mì.',
    nguyenLieuEn: 'Field frog, coconut milk, curry powder, minced lemongrass, roasted peanuts, Vietnamese coriander, baguette.',
    cheBien: 'Ếch chiên sơ cho săn rồi xào với sả và cà ri, chan nước cốt dừa vào cuối và chỉ đun nhỏ lửa để nước cốt không bị tách dầu.',
    cheBienEn: 'The frog is seared, sautéed with lemongrass and curry, then finished with coconut milk over a low flame so the cream does not split.',
    luuY: 'Thịt ếch có nhiều xương nhỏ, cẩn thận với trẻ nhỏ. Có đậu phộng.',
    luuYEn: 'Frog has many small bones; take care with young children. Contains peanuts.',
    tim: 'frog curry dish',
  },
  {
    slug: 'luon-um-nuoc-dua', dm: 'chinh', gia: 325000, phut: 40,
    ten: 'Lươn um nước dừa', tenEn: 'Eel braised in coconut milk',
    mota: 'Lươn đồng um rau ngổ, nước cốt dừa',
    motaEn: 'Field eel braised with rice paddy herb and coconut milk',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Lươn đồng, nước cốt dừa, rau ngổ, sả, nghệ, đậu phộng, bún tươi.',
    nguyenLieuEn: 'Field eel, coconut milk, rice paddy herb, lemongrass, turmeric, peanuts, fresh vermicelli.',
    cheBien: 'Lươn tuốt nhớt bằng tro và muối chứ không cạo, giữ được lớp da. Um nhỏ lửa bốn mươi phút cho thịt mềm mà không nát.',
    cheBienEn: 'The eel is cleaned of slime with ash and salt rather than scraped, which keeps the skin intact, then braised gently for forty minutes until tender but whole.',
    luuY: 'Um lâu nên đặt trước. Lươn có mùi đặc trưng, khách chưa ăn bao giờ nên gọi phần nhỏ.',
    luuYEn: 'The long braise means ordering ahead. Eel has a distinctive aroma; order a small portion if it is new to you.',
    tim: 'eel coconut dish',
  },
  {
    slug: 'ga-nuong-muoi-ot', dm: 'chinh', gia: 420000, phut: 45,
    ten: 'Gà nướng muối ớt', tenEn: 'Chicken grilled with chilli salt',
    mota: 'Gà ta nguyên con, nướng than hoa',
    motaEn: 'Whole free-range chicken over charcoal',
    phan: 'Nguyên con, 4-6 người', phanEn: 'Whole bird, serves 4-6',
    nguyenLieu: 'Gà ta nguyên con, muối hột, ớt hiểm, sả, mật ong, lá chanh, muối tiêu chanh.',
    nguyenLieuEn: 'Whole free-range chicken, coarse salt, bird chilli, lemongrass, honey, kaffir lime leaf, salt-pepper-lime dip.',
    cheBien: 'Gà ướp muối ớt và sả qua đêm, nướng than xoay đều bốn mươi lăm phút. Phết mật ong ở mười phút cuối cho da vàng bóng mà không cháy.',
    cheBienEn: 'The bird marinates overnight in chilli salt and lemongrass, then turns over charcoal for forty-five minutes. Honey is brushed on in the last ten minutes so the skin glazes without burning.',
    luuY: 'Nướng gần một tiếng, bắt buộc đặt trước. Món cay, bên mình làm không cay nếu báo trước.',
    luuYEn: 'Nearly an hour on the grill, so it must be ordered ahead. Spicy by default; we can leave the chilli out on request.',
    tim: 'grilled chicken Vietnamese',
  },
  {
    slug: 'ga-hap-la-sen', dm: 'chinh', gia: 460000, phut: 50,
    ten: 'Gà hấp lá sen', tenEn: 'Chicken steamed in lotus leaf',
    mota: 'Gà ta gói lá sen, hấp cách thủy',
    motaEn: 'Free-range chicken wrapped in lotus leaf and steamed',
    phan: 'Nguyên con, 4-6 người', phanEn: 'Whole bird, serves 4-6',
    nguyenLieu: 'Gà ta, lá sen tươi, hạt sen, nấm đông cô, gừng, rượu trắng, muối tiêu chanh.',
    nguyenLieuEn: 'Free-range chicken, fresh lotus leaf, lotus seeds, shiitake mushroom, ginger, rice wine, salt-pepper-lime dip.',
    cheBien: 'Gà nhồi hạt sen và nấm, gói kín trong lá sen tươi rồi hấp năm mươi phút. Lá sen giữ hơi nước lại và để mùi sen ngấm vào thịt.',
    cheBienEn: 'The bird is stuffed with lotus seeds and mushroom, sealed in fresh lotus leaf and steamed for fifty minutes. The leaf traps the steam and lends its scent to the meat.',
    luuY: 'Hấp gần một tiếng, bắt buộc đặt trước. Lá sen theo mùa, hết mùa bên mình sẽ báo trước.',
    luuYEn: 'Nearly an hour to steam, so it must be ordered ahead. Lotus leaf is seasonal and we will tell you when it is unavailable.',
    tim: 'lotus leaf chicken',
  },
  {
    slug: 'bo-nuong-la-cach', dm: 'chinh', gia: 275000, phut: 25,
    ten: 'Bò nướng lá cách', tenEn: 'Beef grilled in premna leaf',
    mota: 'Bò tơ cuốn lá cách, nướng vỉ than',
    motaEn: 'Young beef wrapped in premna leaf over charcoal',
    phan: 'Phần 10 cuốn', phanEn: '10 rolls',
    nguyenLieu: 'Bò tơ, lá cách, sả, tỏi, mỡ chài, đậu phộng, mắm nêm.',
    nguyenLieuEn: 'Young beef, premna leaf, lemongrass, garlic, caul fat, peanuts, fermented anchovy sauce.',
    cheBien: 'Thịt bò ướp sả tỏi cuốn lá cách, bọc thêm lớp mỡ chài mỏng để khi nướng mỡ chảy ra giữ cho thịt không khô.',
    cheBienEn: 'The seasoned beef is wrapped in premna leaf and a thin layer of caul fat, which melts on the grill and keeps the meat from drying.',
    luuY: 'Nướng than có khói, không đặt được ở phòng máy lạnh kín. Mắm nêm mùi đậm, bên mình có nước mắm thay thế.',
    luuYEn: 'Charcoal grilling produces smoke and cannot be set up in a sealed air-conditioned room. The anchovy sauce is pungent; fish sauce is available instead.',
    tim: 'grilled beef leaf Vietnamese',
  },
  {
    slug: 'heo-rung-xao-sa-ot', dm: 'chinh', gia: 355000, phut: 25,
    ten: 'Heo rừng xào sả ớt', tenEn: 'Wild boar sautéed with lemongrass and chilli',
    mota: 'Thịt heo rừng nuôi, da dày và giòn',
    motaEn: 'Farmed wild boar with thick, crunchy skin',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Thịt heo rừng nuôi, sả băm, ớt hiểm, lá chanh, hành tây, nước mắm, tiêu.',
    nguyenLieuEn: 'Farmed wild boar, minced lemongrass, bird chilli, kaffir lime leaf, onion, fish sauce, pepper.',
    cheBien: 'Thịt thái mỏng ngang thớ rồi xào lửa lớn thật nhanh, sả phi vàng riêng để không bị cháy đắng khi xào chung.',
    cheBienEn: 'The meat is sliced thin across the grain and flashed over high heat; the lemongrass is fried golden separately so it does not scorch bitter in the pan.',
    luuY: 'Thịt heo rừng dai hơn heo thường, đó là đặc trưng. Món cay, điều chỉnh được nếu báo trước.',
    luuYEn: 'Wild boar is chewier than farmed pork, which is the point. Spicy by default and adjustable on request.',
    tim: 'wild boar stir fry',
  },
  {
    slug: 'rau-muong-xao-toi', dm: 'chinh', gia: 75000, phut: 10,
    ten: 'Rau muống xào tỏi', tenEn: 'Water spinach stir-fried with garlic',
    mota: 'Món chay, xào lửa lớn giữ độ giòn',
    motaEn: 'Vegetarian, flashed over high heat to stay crisp',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Rau muống, tỏi, dầu ăn, nước mắm chay hoặc nước tương, tiêu.',
    nguyenLieuEn: 'Water spinach, garlic, oil, vegetarian fish sauce or soy sauce, pepper.',
    cheBien: 'Chảo phải nóng già, xào từng mẻ nhỏ trong chưa đầy hai phút. Xào lâu rau sẽ ra nước và mất màu xanh.',
    cheBienEn: 'The wok must be scorching and each small batch takes under two minutes. Cook it longer and the greens weep and lose their colour.',
    luuY: 'Món chay hoàn toàn nếu dùng nước tương, báo trước khi gọi.',
    luuYEn: 'Fully vegetarian when made with soy sauce — say so when ordering.',
    tim: 'water spinach garlic stir fry',
  },
  {
    slug: 'dau-hu-sot-ca-chua', dm: 'chinh', gia: 85000, phut: 20,
    ten: 'Đậu hũ sốt cà chua', tenEn: 'Tofu in tomato sauce',
    mota: 'Món chay, cà chua chín nấu nhừ',
    motaEn: 'Vegetarian, made with ripe tomatoes cooked down',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Đậu hũ chiên, cà chua chín, hành lá, thì là, nước tương, đường, tiêu.',
    nguyenLieuEn: 'Fried tofu, ripe tomato, spring onion, dill, soy sauce, sugar, pepper.',
    cheBien: 'Cà chua nấu nhừ thành sốt sánh trước, sau đó mới thả đậu hũ vào rim nhẹ để đậu thấm mà không nát.',
    cheBienEn: 'The tomatoes are cooked down to a thick sauce first, then the tofu is simmered gently in it so it takes on flavour without falling apart.',
    luuY: 'Món chay hoàn toàn. Vị nhẹ, hợp ăn kèm với các món đậm.',
    luuYEn: 'Fully vegetarian. Mild in flavour and best alongside the stronger dishes.',
    tim: 'tofu tomato sauce',
  },
  {
    slug: 'nam-kho-tieu-chay', dm: 'chinh', gia: 115000, phut: 25,
    ten: 'Nấm kho tiêu chay', tenEn: 'Mushrooms braised with pepper',
    mota: 'Món chay, nấm đùi gà kho tộ',
    motaEn: 'Vegetarian, king oyster mushrooms in a clay pot',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Nấm đùi gà, nấm rơm, tiêu xanh, nước tương, đường thốt nốt, hành boa rô.',
    nguyenLieuEn: 'King oyster mushroom, straw mushroom, green peppercorns, soy sauce, palm sugar, leek.',
    cheBien: 'Nấm xé sợi rồi áp chảo cho ráo nước trước khi kho, nếu kho ngay thì nấm ra nước và nồi kho bị loãng.',
    cheBienEn: 'The mushrooms are torn into strips and dry-seared to drive off moisture before braising; skip that and they water down the pot.',
    luuY: 'Món chay hoàn toàn. Tiêu xanh cay nồng, giảm được nếu khách báo trước.',
    luuYEn: 'Fully vegetarian. The green peppercorns are pungent and can be reduced on request.',
    tim: 'braised mushroom clay pot',
  },
  {
    slug: 'canh-kho-qua-nhoi-thit', dm: 'chinh', gia: 125000, phut: 35,
    ten: 'Canh khổ qua nhồi thịt', tenEn: 'Bitter melon soup stuffed with pork',
    mota: 'Món Tết quen thuộc, vị đắng dịu',
    motaEn: 'A Lunar New Year staple with a gentle bitterness',
    phan: 'Nồi 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Khổ qua, thịt bằm, mộc nhĩ, miến, hành lá, nước hầm xương, tiêu.',
    nguyenLieuEn: 'Bitter melon, minced pork, wood-ear mushroom, glass noodles, spring onion, pork bone broth, pepper.',
    cheBien: 'Khổ qua móc ruột, nhồi thịt rồi hầm nhỏ lửa ba mươi lăm phút cho vỏ mềm và vị đắng dịu lại chứ không gắt.',
    cheBienEn: 'The melon is cored, stuffed and simmered gently for thirty-five minutes until the skin softens and the bitterness mellows rather than bites.',
    luuY: 'Vị đắng là đặc trưng của món, trẻ nhỏ thường không hợp. Hầm lâu nên đặt trước.',
    luuYEn: 'The bitterness is the point of the dish and children rarely take to it. The long simmer means ordering ahead.',
    tim: 'bitter melon soup Vietnamese',
  },
  {
    slug: 'chim-cut-roti', dm: 'chinh', gia: 265000, phut: 30,
    ten: 'Chim cút rô ti', tenEn: 'Roasted quail',
    mota: 'Cút nguyên con rô ti sốt sánh',
    motaEn: 'Whole quail roasted in a thick glaze',
    phan: 'Phần 6 con', phanEn: '6 birds',
    nguyenLieu: 'Chim cút, ngũ vị hương, mật ong, nước tương, tỏi, gừng, xôi trắng ăn kèm.',
    nguyenLieuEn: 'Quail, five-spice, honey, soy sauce, garlic, ginger, plain sticky rice on the side.',
    cheBien: 'Cút ướp ngũ vị nửa ngày, chiên sơ cho vàng rồi rô ti trong nước sốt đến khi sốt sánh bám quanh mình chim.',
    cheBienEn: 'The quail marinate half a day in five-spice, are seared golden, then roasted in the sauce until it reduces and coats each bird.',
    luuY: 'Chim cút xương nhỏ và nhiều, cẩn thận với trẻ nhỏ. Ăn bằng tay là hợp nhất.',
    luuYEn: 'Quail bones are small and plentiful; take care with young children. Best eaten with your hands.',
    tim: 'roasted quail',
  },
];
