// Món chính, đợt một: mười lăm món cơm, cá và thịt.
module.exports = [
  {
    slug: 'ca-tai-tuong-chien-xu', dm: 'chinh', gia: 385000, phut: 30,
    ten: 'Cá tai tượng chiên xù', tenEn: 'Whole crispy elephant-ear fish',
    mota: 'Chiên nguyên con, cuốn bánh tráng rau sống',
    motaEn: 'Fried whole, rolled in rice paper with herbs',
    phan: 'Phần 4-6 người', phanEn: 'Serves 4-6',
    nguyenLieu: 'Cá tai tượng nguyên con, bánh tráng, bún tươi, xoài xanh, chuối chát, rau sống, nước mắm me.',
    nguyenLieuEn: 'Whole elephant-ear fish, rice paper, vermicelli, green mango, green banana, garden herbs, tamarind fish sauce.',
    cheBien: 'Cá để nguyên vảy chiên ngập dầu, dựng đứng trên đĩa. Vảy cá phồng lên giòn tan, thịt bên trong vẫn mềm và ngọt.',
    cheBienEn: 'The fish is deep-fried with the scales on and stood upright on the plate. The scales puff into crisp shards while the flesh underneath stays soft and sweet.',
    luuY: 'Chiên mất khoảng nửa tiếng nên đặt trước. Cá có xương, cẩn thận với trẻ nhỏ.',
    luuYEn: 'Frying takes about half an hour, so please order ahead. The fish has bones; take care with small children.',
    tim: 'fried whole fish Vietnamese',
  },
  {
    slug: 'ca-kho-to-mien-tay', dm: 'chinh', gia: 245000, phut: 40,
    ten: 'Cá kho tộ miền Tây', tenEn: 'Mekong clay-pot braised fish',
    mota: 'Cá basa kho nước dừa, tiêu xanh',
    motaEn: 'Basa fish braised in coconut water with green peppercorns',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Cá basa cắt khúc, nước dừa xiêm, nước màu dừa, tiêu xanh, hành tím, ớt, hành lá.',
    nguyenLieuEn: 'Basa fish steaks, young coconut water, coconut caramel, green peppercorns, shallot, chilli, spring onion.',
    cheBien: 'Cá ướp nước màu dừa rồi kho trong tộ đất ở lửa liu riu bốn mươi phút, đến khi nước kho sánh lại bám quanh miếng cá.',
    cheBienEn: 'The fish is marinated in coconut caramel, then braised in a clay pot over a low flame for forty minutes until the sauce reduces and clings to each piece.',
    luuY: 'Kho tộ cần bốn mươi phút, đặt sát giờ sẽ phải chờ. Món mặn đậm, ăn kèm cơm trắng và canh chua.',
    luuYEn: 'Clay-pot braising needs forty minutes, so ordering at the last minute means waiting. Deliberately salty and meant to be eaten with plain rice and a sour soup.',
    tim: 'ca kho to Vietnamese braised fish',
  },
  {
    slug: 'canh-chua-ca-loc', dm: 'chinh', gia: 215000, phut: 25,
    ten: 'Canh chua cá lóc', tenEn: 'Sour soup with snakehead fish',
    mota: 'Me chín, bạc hà, đậu bắp, giá',
    motaEn: 'Ripe tamarind with taro stem, okra and bean sprouts',
    phan: 'Nồi 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Cá lóc đồng, me chín, bạc hà, đậu bắp, cà chua, thơm, giá đỗ, ngò om, tỏi phi.',
    nguyenLieuEn: 'Wild snakehead fish, ripe tamarind, taro stem, okra, tomato, pineapple, bean sprouts, rice paddy herb, fried garlic.',
    cheBien: 'Vị chua lấy từ me chín dầm chứ không dùng giấm. Rau thả vào sau cùng, vừa chín tới là tắt bếp để bạc hà còn giòn.',
    cheBienEn: 'The sourness comes from mashed ripe tamarind, never vinegar. The vegetables go in last and the pot comes off the heat the moment they are done, so the taro stem keeps its crunch.',
    luuY: 'Cá lóc đồng có xương dăm. Món chua, khách đau dạ dày nên cân nhắc.',
    luuYEn: 'Wild snakehead carries fine bones. The soup is sour and may not suit a sensitive stomach.',
    tim: 'canh chua Vietnamese sour soup',
  },
  {
    slug: 'thit-kho-trung-nuoc-dua', dm: 'chinh', gia: 225000, phut: 45,
    ten: 'Thịt kho trứng nước dừa', tenEn: 'Pork and eggs braised in coconut water',
    mota: 'Ba chỉ kho rục, trứng vịt thấm màu',
    motaEn: 'Pork belly braised soft with colour-stained duck eggs',
    phan: 'Phần 4-6 người', phanEn: 'Serves 4-6',
    nguyenLieu: 'Thịt ba chỉ, trứng vịt luộc, nước dừa xiêm, nước màu, hành tím, tiêu, dưa giá ăn kèm.',
    nguyenLieuEn: 'Pork belly, boiled duck eggs, young coconut water, caramel, shallot, pepper, pickled bean sprouts on the side.',
    cheBien: 'Thịt kho trong nước dừa bốn mươi lăm phút cho mỡ trong và mềm rục. Trứng luộc bóc vỏ kho cùng nửa tiếng cuối để thấm màu đều.',
    cheBienEn: 'The pork braises in coconut water for forty-five minutes until the fat turns clear and yields. The peeled eggs join for the last half hour so they take on an even colour.',
    luuY: 'Món nhiều mỡ, khách kiêng dầu mỡ nên chọn món khác. Kho lâu nên cần đặt trước.',
    luuYEn: 'A rich, fatty dish — choose something else if you are avoiding fat. The long braise means it must be ordered ahead.',
    tim: 'thit kho tau Vietnamese braised pork',
  },
  {
    slug: 'suon-ram-man', dm: 'chinh', gia: 235000, phut: 30,
    ten: 'Sườn ram mặn', tenEn: 'Caramelised pork ribs',
    mota: 'Sườn cốt lết ram đường thốt nốt',
    motaEn: 'Pork chop ribs caramelised in palm sugar',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Sườn cốt lết, đường thốt nốt, nước mắm, tỏi, hành tím, tiêu, hành lá.',
    nguyenLieuEn: 'Pork chop ribs, palm sugar, fish sauce, garlic, shallot, pepper, spring onion.',
    cheBien: 'Sườn chiên sơ cho vàng cạnh rồi ram với đường thốt nốt thắng cháy, đảo liên tục cho nước sốt bám đều và bóng.',
    cheBienEn: 'The ribs are seared golden, then tossed in burnt palm sugar caramel and stirred constantly so the glaze coats them evenly and shines.',
    luuY: 'Món ngọt mặn đậm, ăn kèm cơm trắng. Sườn có xương.',
    luuYEn: 'Sweet and salty, meant for plain rice. The ribs are bone-in.',
    tim: 'caramelized pork ribs Vietnamese',
  },
  {
    slug: 'ga-kho-gung', dm: 'chinh', gia: 265000, phut: 35,
    ten: 'Gà kho gừng', tenEn: 'Chicken braised with ginger',
    mota: 'Gà ta chặt miếng, gừng non thái sợi',
    motaEn: 'Free-range chicken with shredded young ginger',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Gà ta, gừng non, nước mắm, đường, tiêu, hành tím, ớt.',
    nguyenLieuEn: 'Free-range chicken, young ginger, fish sauce, sugar, pepper, shallot, chilli.',
    cheBien: 'Gừng non thái sợi phi thơm trước, sau đó mới cho gà vào kho để mùi gừng ngấm vào thịt chứ không nổi riêng một bên.',
    cheBienEn: 'The young ginger is fried until fragrant before the chicken goes in, so its warmth runs through the meat instead of sitting on top.',
    luuY: 'Gà ta dai hơn gà công nghiệp, đó là đặc trưng. Gừng cay nồng, trẻ nhỏ có thể không hợp.',
    luuYEn: 'Free-range chicken is firmer than farmed chicken, which is the point. The ginger is pungent and may not suit young children.',
    tim: 'chicken ginger Vietnamese braised',
  },
  {
    slug: 'vit-quay-la-mac-mat', dm: 'chinh', gia: 520000, phut: 50,
    ten: 'Vịt quay lá mắc mật', tenEn: 'Roast duck with mac mat leaves',
    mota: 'Vịt nguyên con, da giòn, lá mắc mật Lạng Sơn',
    motaEn: 'Whole duck with crisp skin and Lang Son mac mat leaves',
    phan: 'Nguyên con, 4-6 người', phanEn: 'Whole bird, serves 4-6',
    nguyenLieu: 'Vịt cỏ nguyên con, lá mắc mật, mật ong, hoa hồi, quế, xì dầu, nước chấm mắc mật.',
    nguyenLieuEn: 'Whole free-range duck, mac mat leaves, honey, star anise, cinnamon, soy sauce, mac mat dipping sauce.',
    cheBien: 'Nhồi lá mắc mật vào bụng vịt, phết mật ong lên da rồi quay năm mươi phút. Da phồng giòn còn lá bên trong hãm mùi hôi và tỏa hương vào thịt.',
    cheBienEn: 'Mac mat leaves are packed into the cavity, honey brushed over the skin, and the duck roasts for fifty minutes. The skin blisters crisp while the leaves inside tame the gaminess and scent the meat.',
    luuY: 'Quay mất gần một tiếng, bắt buộc đặt trước ít nhất một buổi. Thịt vịt có mùi đặc trưng.',
    luuYEn: 'Roasting takes nearly an hour and must be ordered at least one session ahead. Duck has a distinctive aroma.',
    tim: 'roast duck Vietnamese',
  },
  {
    slug: 'bo-luc-lac-khoai-tay', dm: 'chinh', gia: 345000, phut: 20,
    ten: 'Bò lúc lắc khoai tây', tenEn: 'Shaking beef with potatoes',
    mota: 'Thăn bò cắt vuông, áp chảo lửa lớn',
    motaEn: 'Cubed beef tenderloin seared over high heat',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Thăn bò, khoai tây chiên, hành tây, ớt chuông, xà lách xoong, nước sốt tiêu đen.',
    nguyenLieuEn: 'Beef tenderloin, fried potato, onion, bell pepper, watercress, black pepper sauce.',
    cheBien: 'Chảo phải thật nóng, đảo nhanh từng mẻ nhỏ để bò xém ngoài mà trong còn hồng. Đảo nhiều quá thì bò ra nước và dai.',
    cheBienEn: 'The pan must be searing hot and the beef tossed quickly in small batches so it chars outside and stays pink within. Overcrowd it and the beef weeps and toughens.',
    luuY: 'Bên mình làm chín vừa theo mặc định, khách muốn chín kỹ báo trước. Món có hành tây.',
    luuYEn: 'Cooked medium by default; tell us if you would like it well done. Contains onion.',
    tim: 'shaking beef Vietnamese bo luc lac',
  },
  {
    slug: 'com-chien-hai-san-trai-thom', dm: 'chinh', gia: 285000, phut: 25,
    ten: 'Cơm chiên hải sản trái thơm', tenEn: 'Seafood fried rice in a pineapple',
    mota: 'Dọn trong nửa trái thơm nướng',
    motaEn: 'Served in half a roasted pineapple',
    phan: 'Phần 3-4 người', phanEn: 'Serves 3-4',
    nguyenLieu: 'Cơm nguội, tôm, mực, chả cá, trứng, thơm, đậu Hà Lan, hành lá, nước mắm.',
    nguyenLieuEn: 'Day-old rice, prawn, squid, fish cake, egg, pineapple, green peas, spring onion, fish sauce.',
    cheBien: 'Dùng cơm nguội để hạt rời chứ không bết. Chiên lửa lớn từng mẻ, dọn trong nửa trái thơm đã khoét ruột và nướng sơ.',
    cheBienEn: 'Made with day-old rice so the grains stay separate. Fried in batches over high heat and served in a hollowed, lightly roasted pineapple half.',
    luuY: 'Có hải sản, khách dị ứng báo trước để bên mình đổi sang cơm chiên gà.',
    luuYEn: 'Contains seafood; tell us in advance and we will make it with chicken instead.',
    tim: 'pineapple fried rice',
  },
  {
    slug: 'com-nieu-dap-nieu', dm: 'chinh', gia: 165000, phut: 40,
    ten: 'Cơm niêu đập niêu', tenEn: 'Clay-pot rice cracked at the table',
    mota: 'Nấu niêu đất, đập niêu ngay tại bàn',
    motaEn: 'Cooked in a clay pot and cracked open at your table',
    phan: 'Niêu 4-6 người', phanEn: 'Pot for 4-6',
    nguyenLieu: 'Gạo thơm, niêu đất, mỡ hành, nước mắm kho quẹt, cá khô ăn kèm.',
    nguyenLieuEn: 'Fragrant rice, clay pot, scallion oil, kho quet dipping sauce, dried fish on the side.',
    cheBien: 'Cơm nấu trong niêu đất bốn mươi phút cho đáy niêu đóng lớp cháy vàng. Nhân viên đập niêu ngay tại bàn để khách thấy lớp cơm cháy còn nguyên.',
    cheBienEn: 'The rice cooks in a clay pot for forty minutes until a golden crust forms at the base. A server cracks the pot at your table so you see the crust intact.',
    luuY: 'Nấu mất bốn mươi phút, nên gọi ngay từ đầu bữa. Đập niêu có tiếng động lớn, báo trước nếu bàn có trẻ nhỏ hay người lớn tuổi.',
    luuYEn: 'Forty minutes to cook, so order it at the start of the meal. Cracking the pot is loud — tell us if there are small children or elderly guests at the table.',
    tim: 'clay pot rice Vietnamese com nieu',
  },
  {
    slug: 'bun-thit-nuong-cha-gio', dm: 'chinh', gia: 125000, phut: 20,
    ten: 'Bún thịt nướng chả giò', tenEn: 'Vermicelli with grilled pork and spring rolls',
    mota: 'Bún tươi, thịt nướng than, chả giò cắt khúc',
    motaEn: 'Fresh vermicelli, charcoal-grilled pork and sliced spring rolls',
    phan: 'Phần 1 tô lớn', phanEn: 'One large bowl',
    nguyenLieu: 'Bún tươi, thịt nạc vai nướng, chả giò, xà lách, giá, dưa leo, đậu phộng, nước mắm chua ngọt.',
    nguyenLieuEn: 'Fresh vermicelli, grilled pork shoulder, spring rolls, lettuce, bean sprouts, cucumber, peanuts, sweet-and-sour fish sauce.',
    cheBien: 'Thịt ướp sả tỏi nướng than cho xém cạnh. Chả giò chiên lại lần hai ngay trước khi dọn để giữ độ giòn khi chan nước mắm.',
    cheBienEn: 'The pork is marinated with lemongrass and garlic and grilled until the edges char. The spring rolls are fried a second time just before serving so they stay crisp under the dressing.',
    luuY: 'Món một người ăn, không phải món chia bàn. Có đậu phộng.',
    luuYEn: 'A single-serve bowl, not a sharing dish. Contains peanuts.',
    tim: 'bun thit nuong Vietnamese',
  },
  {
    slug: 'mi-quang-ga', dm: 'chinh', gia: 115000, phut: 25,
    ten: 'Mì Quảng gà', tenEn: 'Quang noodles with chicken',
    mota: 'Sợi mì vàng, nước dùng xăm xắp, bánh tráng mè',
    motaEn: 'Yellow noodles in a shallow broth with sesame rice crackers',
    phan: 'Phần 1 tô lớn', phanEn: 'One large bowl',
    nguyenLieu: 'Mì Quảng sợi vàng, gà ta, nghệ tươi, đậu phộng rang, bánh tráng mè, rau sống, hành phi.',
    nguyenLieuEn: 'Yellow Quang noodles, free-range chicken, fresh turmeric, roasted peanuts, sesame rice cracker, garden herbs, fried shallots.',
    cheBien: 'Nước dùng nấu đậm và chỉ chan xăm xắp chứ không ngập như phở, để sợi mì thấm chứ không loãng. Bánh tráng mè bẻ vào ăn cùng.',
    cheBienEn: 'The broth is cooked strong and ladled only halfway up the bowl rather than covering the noodles, so the flavour clings instead of thinning. The sesame cracker is broken in as you eat.',
    luuY: 'Ít nước dùng là đúng kiểu Quảng Nam, không phải bên mình chan thiếu. Có đậu phộng.',
    luuYEn: 'The shallow broth is how Quang Nam serves it, not a short measure. Contains peanuts.',
    tim: 'mi quang Vietnamese noodle',
  },
  {
    slug: 'hu-tieu-nam-vang', dm: 'chinh', gia: 105000, phut: 25,
    ten: 'Hủ tiếu Nam Vang', tenEn: 'Nam Vang noodle soup',
    mota: 'Nước trong, tôm thịt, gan và trứng cút',
    motaEn: 'Clear broth with prawn, pork, liver and quail eggs',
    phan: 'Phần 1 tô lớn', phanEn: 'One large bowl',
    nguyenLieu: 'Hủ tiếu dai, tôm, thịt bằm, gan heo, trứng cút, tỏi phi, hẹ, nước hầm xương.',
    nguyenLieuEn: 'Chewy rice noodles, prawn, minced pork, pork liver, quail eggs, fried garlic, garlic chives, pork bone broth.',
    cheBien: 'Xương hầm bốn tiếng rồi lọc kỹ cho nước thật trong. Tôm và gan trụng riêng từng phần để không làm đục nồi nước dùng.',
    cheBienEn: 'The bones simmer four hours and the broth is strained until clear. Prawn and liver are blanched separately for each bowl so they do not cloud the pot.',
    luuY: 'Có hải sản và nội tạng, khách kiêng báo trước để bên mình bỏ bớt.',
    luuYEn: 'Contains shellfish and offal; tell us in advance and we will leave them out.',
    tim: 'hu tieu Nam Vang noodle soup',
  },
  {
    slug: 'banh-canh-cua', dm: 'chinh', gia: 135000, phut: 30,
    ten: 'Bánh canh cua', tenEn: 'Thick noodle soup with crab',
    mota: 'Sợi bột gạo, nước dùng sánh, thịt cua tươi',
    motaEn: 'Thick rice noodles in a glossy broth with fresh crab',
    phan: 'Phần 1 tô lớn', phanEn: 'One large bowl',
    nguyenLieu: 'Bánh canh bột gạo, thịt cua, chả cua, huyết, trứng cút, hành lá, tiêu, nước hầm xương.',
    nguyenLieuEn: 'Thick rice noodles, crab meat, crab cake, blood cake, quail eggs, spring onion, pepper, pork bone broth.',
    cheBien: 'Nước dùng làm sánh bằng chính bột gạo của sợi bánh canh chứ không pha bột năng. Thịt cua gỡ tay, thả vào sau cùng để không nát.',
    cheBienEn: 'The broth is thickened by the starch from the noodles themselves rather than added tapioca. The crab is picked by hand and folded in last so it does not break up.',
    luuY: 'Có hải sản. Món có huyết, khách không dùng báo trước để bên mình bỏ ra.',
    luuYEn: 'Contains shellfish. The bowl includes blood cake; tell us if you would rather it was left out.',
    tim: 'banh canh cua Vietnamese',
  },
  {
    slug: 'bo-kho-banh-mi', dm: 'chinh', gia: 145000, phut: 45,
    ten: 'Bò kho bánh mì', tenEn: 'Beef stew with baguette',
    mota: 'Bắp bò hầm mềm, cà rốt, sả quế',
    motaEn: 'Beef shank stewed soft with carrot, lemongrass and cinnamon',
    phan: 'Phần 2-3 người', phanEn: 'Serves 2-3',
    nguyenLieu: 'Bắp bò, cà rốt, sả, quế, hoa hồi, cà chua, nước dừa, bánh mì nóng, rau quế.',
    nguyenLieuEn: 'Beef shank, carrot, lemongrass, cinnamon, star anise, tomato, coconut water, warm baguette, Thai basil.',
    cheBien: 'Bắp bò hầm bốn mươi lăm phút với sả quế cho mềm mà vẫn giữ thớ. Cà rốt cho vào nửa tiếng cuối để không bị nát.',
    cheBienEn: 'The shank stews for forty-five minutes with lemongrass and cinnamon until tender but still fibrous. The carrot goes in for the last half hour so it does not collapse.',
    luuY: 'Hầm lâu nên đặt trước. Bánh mì nướng lại khi dọn, hết bánh bên mình sẽ báo.',
    luuYEn: 'The long stew means ordering ahead. The baguette is re-toasted on serving; if we run out we will say so.',
    tim: 'bo kho Vietnamese beef stew',
  },
];
